sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build . -t rgdevops123/devopsweb
  - docker run -d --rm --name devopsweb -p 5000:5000 --env DEVOPSWEB_CONFIG_MODE=Test1 rgdevops123/devopsweb
  - docker ps -a

script:
  - docker exec -it -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" devopsweb /bin/bash -c "pytest -v --disable-pytest-warnings"

after_success:
  - coveralls
